sudo: required

language: go

go:
  - "1.12.5"

os:
  - linux
  - osx

# Just because it has java8 pre-installed.
osx_image: xcode9.3

addons:
  homebrew:
    packages:
    - wget
    - unzip
  apt:
    packages:
    - wget
    - unzip
    - default-jdk

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source .travis/download-sdk-tools-linux; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then source .travis/download-sdk-tools-darwin; fi
  - source .travis/install-sdk-ndk

install:
  - echo "Getting deps"
  - go get -d ./...
  - echo "Installing gomobile"
  - go get golang.org/x/mobile/cmd/gomobile
  - go install golang.org/x/mobile/cmd/gomobile
  - gomobile init

script:
  - echo "Building"
  # Make android on linux.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make android; ls -l build; fi
  # Make both android and ios on osx.
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make; ls -l build; fi
